### PR TITLE
Dividing code up into "old no-SSL code" and "new shiny TLS code"

### PR DESCRIPTION
**Pull request by pboothe**
First pull request of N

### CODE REVIEW

**Comment by mtlynch** [comment]
A few high level questions:
 * How would you describe this change at a high level? It seems like it replaces all the low-level socket functions with versions that are OpenSSL compatible. Is that right?
 * What does the `_any` suffix mean? How does `send_msg_any` differ from `send_msg`?
 * Will only the server support TLS or does the client support it as well?

**Comment by pboothe** [comment]
This replaces all the low-level networking functions with SSL-compatible versions.  The SSL-compatible versions have _any as a suffix to indicate that they can send over any type of connection.

Once this change is in, the old versions of the functions will be renamed to _raw, and once that is done, then the _any versions will be reverted back to their original names.  But I want to not make changes to the client (which uses these functions too) when I make changes to the server.  So the first step is to make a new name and use the new name everywhere.

**Comment by pboothe** [comment]
The command-line client will not support SSL (or, at least, I have written no code to allow that to happen).  The command-line client is also not a very big source of data, and since it already works I don't want to "fix" it.

**Comment by pboothe** [comment]
PTAL

**Comment by aaronmbr** [comment]
These changes look reasonable. Thanks for the code review Michael :)

**Comment by pboothe** [comment]
Crap!  I did not mean to make a pull request to main ndt!  I mean to make one to mlab ndt!  Aaron, I recommend you back this change out, as I don't think things will still compile with this change in.  There are about 4 more change requests coming, and we weren't even done with this one yet. :)

**Comment by aaronmbr** [comment]
pffft, minor details.

**Comment by pboothe** [comment]
Conversation continues on the private repo pull request, rather than the
mainline one: https://github.com/m-lab/ndt/pull/3

I'll hopefully have the full change available in a week Aaron.  It's +1900
lines and -1700, so it's kind of a big change - it also refactors the
main() in web100srv into 3 semi-readable functions instead of 1 over-large
terrifying thing.

  -Peter

On Wed, May 6, 2015 at 8:12 AM, aaronmbr <notifications@github.com> wrote:

> pffft, minor details.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndt-project/ndt/pull/187#issuecomment-99427155>.
>



-- 
Peter Boothe | ɯoɔ˙ǝlƃooƃ@ǝɥʇooqd <pboothe@google.com> | ᴹ̶LAB |
http://measurementlab.net

**Comment by aaronmbr** [comment]
I will be very much looking forward to seeing it refactored. The main() function was among the many rather terrifying pieces of code in there :)

**Pull request merged**
